/**
 * An enum containing the error and where it happened.
 * Mainly used for logging purposes.
 */
export enum ErrorTitle {
  ERROR_ADDING_MULTIPLE_USERS = 'ERROR ADDING MULTIPLE USERS',
  ERROR_ADDING_SINGLE_USER = 'ERROR ADDING SINGLE USER',
  ERROR_CREATING_EVENT = 'ERROR CREATING EVENT',
  ERROR_CREATING_SINGLE_APPLICANT = 'ERROR ADDING SINGLE APPLICANT',
}
